import { readFile, writeFile } from "node:fs/promises";
import { basename, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
import { parseRecipeCsv } from "../src/data/recipeCsv.ts";
import {
  MINIMUM_PUBLIC_RECIPE_COVERAGE,
  normalizePublicRecipeRecord,
} from "../src/data/recipeCatalog.ts";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const inputPath = process.argv[2];
const outputPath = resolve(
  repositoryRoot,
  process.argv[3] ?? "src/data/publicRecipes.ts",
);
const sourceSnapshotDate = process.argv[4] ?? "unknown";
const acquiredDate = process.argv[5] ?? "unknown";

if (!inputPath) {
  throw new Error(
    "사용법: node scripts/generateRecipeCatalog.mjs <CSV 경로> [출력 경로] [데이터 기준일 YYYY-MM-DD 또는 unknown] [확보일 YYYY-MM-DD 또는 unknown]",
  );
}

for (const [label, date] of [["데이터 기준일", sourceSnapshotDate], ["확보일", acquiredDate]]) {
  const timestamp = Date.parse(`${date}T00:00:00.000Z`);
  if (date !== "unknown" && (!/^\d{4}-\d{2}-\d{2}$/.test(date) || !Number.isFinite(timestamp) || new Date(timestamp).toISOString().slice(0, 10) !== date)) {
    throw new Error(`${label}은 YYYY-MM-DD 또는 unknown이어야 합니다.`);
  }
}

const inputBytes = await readFile(resolve(inputPath));
const records = parseRecipeCsv(inputBytes.toString("utf8"));
const recipes = [];
const excludedByReason = {};

for (const record of records) {
  const result = normalizePublicRecipeRecord(record);
  if (result.recipe) {
    recipes.push(result.recipe);
  } else if (result.exclusionReason) {
    excludedByReason[result.exclusionReason] =
      (excludedByReason[result.exclusionReason] ?? 0) + 1;
  }
}

const recipeIds = new Set(recipes.map(({ id }) => id));
if (recipeIds.size !== recipes.length) {
  throw new Error("정규화 결과에 중복 레시피 ID가 있습니다.");
}

const summary = {
  sourceRecordCount: records.length,
  includedRecordCount: recipes.length,
  excludedRecordCount: records.length - recipes.length,
  excludedByReason,
  minimumIngredientCoverage: MINIMUM_PUBLIC_RECIPE_COVERAGE,
  sourceSnapshotDate,
  acquiredDate,
  sourceFiles: [{ name: basename(resolve(inputPath)), sha256: createHash("sha256").update(inputBytes).digest("hex") }],
};

const output = [
  "// Generated by scripts/generateRecipeCatalog.mjs. Do not edit by hand.",
  'import type { Recipe } from "../types/recipe";',
  "",
  `export const PUBLIC_RECIPE_IMPORT_SUMMARY = ${JSON.stringify(summary, null, 2)} as const;`,
  "",
  `export const PUBLIC_RECIPES: Recipe[] = ${JSON.stringify(recipes, null, 2)};`,
  "",
].join("\n");

await writeFile(outputPath, output, "utf8");
console.log(
  JSON.stringify({
    inputFileName: basename(resolve(inputPath)),
    outputPath: resolve(outputPath),
    ...summary,
  }),
);
