import { readFile, writeFile } from "node:fs/promises";
import { basename, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseRecipeCsv } from "../src/data/recipeCsv.ts";
import {
  MINIMUM_PUBLIC_RECIPE_COVERAGE,
  normalizePublicRecipeRecord,
} from "../src/data/recipeCatalog.ts";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const inputPath = process.argv[2];
const outputPath = resolve(
  repositoryRoot,
  process.argv[3] ?? "src/data/publicRecipes.ts",
);
const sourceSnapshotDate = process.argv[4] ?? "unknown";

if (!inputPath) {
  throw new Error(
    "사용법: node --experimental-strip-types scripts/generateRecipeCatalog.mjs <CSV 경로> [출력 경로] [데이터 기준일 YYYY-MM-DD]",
  );
}

const snapshotTimestamp = Date.parse(`${sourceSnapshotDate}T00:00:00.000Z`);
if (
  sourceSnapshotDate !== "unknown" &&
  (!/^\d{4}-\d{2}-\d{2}$/.test(sourceSnapshotDate) ||
    !Number.isFinite(snapshotTimestamp) ||
    new Date(snapshotTimestamp).toISOString().slice(0, 10) !==
      sourceSnapshotDate)
) {
  throw new Error("데이터 기준일은 YYYY-MM-DD 또는 unknown이어야 합니다.");
}

const records = parseRecipeCsv(await readFile(resolve(inputPath), "utf8"));
const recipes = [];
const excludedByReason = {};

for (const record of records) {
  const result = normalizePublicRecipeRecord(record);
  if (result.recipe) {
    recipes.push(result.recipe);
  } else if (result.exclusionReason) {
    excludedByReason[result.exclusionReason] =
      (excludedByReason[result.exclusionReason] ?? 0) + 1;
  }
}

const recipeIds = new Set(recipes.map(({ id }) => id));
if (recipeIds.size !== recipes.length) {
  throw new Error("정규화 결과에 중복 레시피 ID가 있습니다.");
}

const summary = {
  sourceRecordCount: records.length,
  includedRecordCount: recipes.length,
  excludedRecordCount: records.length - recipes.length,
  excludedByReason,
  minimumIngredientCoverage: MINIMUM_PUBLIC_RECIPE_COVERAGE,
  sourceSnapshotDate,
};

const output = [
  "// Generated by scripts/generateRecipeCatalog.mjs. Do not edit by hand.",
  'import type { Recipe } from "../types/recipe";',
  "",
  `export const PUBLIC_RECIPE_IMPORT_SUMMARY = ${JSON.stringify(summary, null, 2)} as const;`,
  "",
  `export const PUBLIC_RECIPES: Recipe[] = ${JSON.stringify(recipes, null, 2)};`,
  "",
].join("\n");

await writeFile(outputPath, output, "utf8");
console.log(
  JSON.stringify({
    inputFileName: basename(resolve(inputPath)),
    outputPath: resolve(outputPath),
    ...summary,
  }),
);
