import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { resolve, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildEpisCatalog, parseEpisCsv } from '../src/data/episCatalog.ts';

const [basicPath, ingredientsPath, stepsPath, outputPath, acquiredDate = 'unknown'] = process.argv.slice(2);
if (!basicPath || !ingredientsPath || !stepsPath) throw new Error('사용법: node scripts/generateEpisCatalog.mjs <기본CSV> <재료JSON> <과정CSV> [출력TS] [확보일 YYYY-MM-DD]');
if (acquiredDate !== 'unknown' && (!/^\d{4}-\d{2}-\d{2}$/.test(acquiredDate) ||
  !Number.isFinite(Date.parse(acquiredDate)) || new Date(acquiredDate).toISOString().slice(0, 10) !== acquiredDate)) throw new Error('확보일 형식 오류');
const inputs = await Promise.all([basicPath, ingredientsPath, stepsPath].map(path => readFile(resolve(path))));
function decode(buffer) {
  try { return new TextDecoder('utf-8', { fatal: true }).decode(buffer); }
  catch { return new TextDecoder('euc-kr', { fatal: true }).decode(buffer); }
}
const basic = parseEpisCsv(decode(inputs[0]), 'basic');
const data = JSON.parse(inputs[1].toString('utf8'));
const steps = parseEpisCsv(decode(inputs[2]), 'steps');
if (!Array.isArray(data.row) || data.totalCnt !== data.row.length) throw new Error('재료 전체 행 수 불일치');
const result = buildEpisCatalog(basic.records, data.row, steps.records);
const excludedByReason = {};
for (const { reason } of result.excluded) excludedByReason[reason] = (excludedByReason[reason] ?? 0) + 1;
const summary = {
  sourceRecordCount: basic.records.length, ingredientRowCount: data.row.length, stepRowCount: steps.records.length,
  includedRecordCount: result.recipes.length, excludedRecordCount: result.excluded.length, excludedByReason,
  excluded: result.excluded, orphanIngredientRecipeIds: result.orphanIngredientRecipeIds,
  orphanStepRecipeIds: result.orphanStepRecipeIds, repairs: steps.repairs,
  minimumIngredientCoverage: 0.6, sourceSnapshotDate: 'unknown', acquiredDate,
  sourceFiles: [basicPath, ingredientsPath, stepsPath].map((path, i) => ({ name: basename(path), sha256: createHash('sha256').update(inputs[i]).digest('hex') })),
};
const target = resolve(outputPath ?? resolve(dirname(fileURLToPath(import.meta.url)), '../src/data/episRecipes.ts'));
await writeFile(target, [
  '// Generated by scripts/generateEpisCatalog.mjs. Do not edit by hand.',
  'import type { Recipe } from "../types/recipe";', '',
  `export const EPIS_RECIPE_IMPORT_SUMMARY = ${JSON.stringify(summary, null, 2)} as const;`, '',
  `export const EPIS_RECIPES: Recipe[] = ${JSON.stringify(result.recipes, null, 2)};`, '',
].join('\n'));
console.log(JSON.stringify({ outputPath: target, ...summary }, null, 2));
